print("    *      " * 2)
print("   * *     " * 2)
print("  *   *    " * 2)
print(" *     *   " * 2)
print("*       *  " * 2)
print("***   ***  " * 2)
print("  *   *    " * 2)
print("  *   *    " * 2)
print("  *   *    " * 2)
print("  *****    " * 2)
print(0x123)
x = 2
